In [122]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

In [123]:
def decomposition(matrix, n):
    for i in range(1,n):
        e_k = matrix[i][i-1]
        f_k_minus_1 = matrix[i-1][i-1]

        matrix[i][i-1] = e_k/f_k_minus_1

        e_k = matrix[i][i-1]
        g_k_minus_1 = matrix[i-1][i]
        matrix[i][i] = matrix[i][i] - e_k*g_k_minus_1
    return matrix

In [124]:
def forward_substitution(matrix, n, r):
    for i in range(1,n):
        e_k = matrix[i][i-1]
        r_k_minus_1 = r[i-1][0]

        r[i][0] = r[i][0] - e_k*r_k_minus_1
    return r

In [125]:
def back_substitution(matrix, n, r):
    x = np.zeros((n,1))
    for i in range(n):
        x[i][0] = r[i][0]/matrix[i][i]
    for k in range(n-2, -1, -1):
        r_k = r[k][0]
        g_k = matrix[k][k+1]
        f_k = matrix[k][k]
        x[k][0] = (r_k - g_k*x[k-1][0])/f_k
    
    return x

In [126]:
def steps(matrix, r):
    n = matrix.shape[0]
    matrix = decomposition(matrix, n) # this will perform the decomposition step and return updated matrix
    r = forward_substitution(matrix, n, r) # this will perform the forward_substitution step and return updated r
    x = back_substitution(matrix, n, r) # this will perform the back_substitution step and find x

    # print(x)
    return x

In [127]:
matrix = np.array([[2.01475, -0.020875, 0, 0],
                  [-0.020875, 2.01475, -0.020875, 0],
                  [0, -0.020875, 2.01475,  -0.020875],
                  [0 , 0,  -0.020875, 2.01475]])

r = np.array([[4.175],[0], [0], [2.0875]])
matrix, r

(array([[ 2.01475, -0.02088,  0.     ,  0.     ],
        [-0.02088,  2.01475, -0.02088,  0.     ],
        [ 0.     , -0.02088,  2.01475, -0.02088],
        [ 0.     ,  0.     , -0.02088,  2.01475]]),
 array([[4.175 ],
        [0.    ],
        [0.    ],
        [2.0875]]))

In [128]:
# np.set_printoptions(precision=2, suppress=True) # for getting only 2 decimal places

x = steps(matrix, r)
print(x)

[[2.08295]
 [0.04295]
 [0.00045]
 [1.03622]]


In [129]:
for i in range(1,5):
    print(f"x{i} = {x[i-1][0]}")

x1 = 2.0829537856315623
x2 = 0.04294545967812426
x3 = 0.00044500942110667254
x4 = 1.0362222563444323
