Gauss elimination - i.e. what we do to make the matrix upper triangular 
main function:
R(j) = R(j) - R(i)*(a(j,i)/a(i,i))

but we have to ensure that the diagonal element i.e. a[i][i] !=0

so for this reason what we do is whenever we go to the next set of iterations
we will do a search for all elements in the same column beneath a[i][i], 
and we will sort them in descending order

In [16]:
import numpy as np

In [17]:
# taking values form assignment
a_list = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5]
g_list = [2.1, 3.5, 5.0, 6.8, 9.2, 12.0, 15.3, 19.1]


In [18]:
# forming matrix A
def give_a_matrix(a_list):
    a = np.zeros((len(a_list),8))
    for i in range(len(a_list)):
        for j in range(8):
            a[i][j] = a_list[i]**j
    return np.round(a,2)

In [19]:
np.set_printoptions(precision=2, suppress=True) # for getting only 2 decimal places
b = np.array(g_list).reshape(-1,1) # reshaped to make 2d matrix
a = give_a_matrix(a_list)

In [20]:
# 2) printing A and b
print("Matrix A: ")
print(a)
print()
print("Matrix b")
print(b)

Matrix A: 
[[    1.       1.       1.       1.       1.       1.       1.       1.  ]
 [    1.       1.5      2.25     3.38     5.06     7.59    11.39    17.09]
 [    1.       2.       4.       8.      16.      32.      64.     128.  ]
 [    1.       2.5      6.25    15.62    39.06    97.66   244.14   610.35]
 [    1.       3.       9.      27.      81.     243.     729.    2187.  ]
 [    1.       3.5     12.25    42.88   150.06   525.22  1838.27  6433.93]
 [    1.       4.      16.      64.     256.    1024.    4096.   16384.  ]
 [    1.       4.5     20.25    91.12   410.06  1845.28  8303.77 37366.95]]

Matrix b
[[ 2.1]
 [ 3.5]
 [ 5. ]
 [ 6.8]
 [ 9.2]
 [12. ]
 [15.3]
 [19.1]]


In [21]:
augmented_matirx = np.concatenate((a,b), axis=1)
print(augmented_matirx)

[[    1.       1.       1.       1.       1.       1.       1.       1.
      2.1 ]
 [    1.       1.5      2.25     3.38     5.06     7.59    11.39    17.09
      3.5 ]
 [    1.       2.       4.       8.      16.      32.      64.     128.
      5.  ]
 [    1.       2.5      6.25    15.62    39.06    97.66   244.14   610.35
      6.8 ]
 [    1.       3.       9.      27.      81.     243.     729.    2187.
      9.2 ]
 [    1.       3.5     12.25    42.88   150.06   525.22  1838.27  6433.93
     12.  ]
 [    1.       4.      16.      64.     256.    1024.    4096.   16384.
     15.3 ]
 [    1.       4.5     20.25    91.12   410.06  1845.28  8303.77 37366.95
     19.1 ]]


In [22]:
def gauss_elimination(a, b):
    l  = np.zeros((len(a), len(a[0])))
    n = len(a)
    c = np.concatenate((a,b), axis=1)
    for i in range(n-1):
        l[i][i]=1
        max_idx_in_bottom = np.argmax(c[i:, i])
        max_row_idx = i + max_idx_in_bottom 

        c[[i, max_row_idx]] = c[[max_row_idx, i]]
        for j in range(i+1, n):
            if(c[i][i]!=0):
                l[j][i] = c[j][i]/c[i][i]
                c[j] = c[j] - c[i]*(c[j][i]/c[i][i])
            # print("forming l: ", l)
    return c, l

In [23]:
c , l= gauss_elimination(a,b)

In [24]:
L = l
U = c[:, :-1]
b_new = c[:, -1].reshape(-1,1) # 


In [25]:
print(L) # Lower triangular matrix

[[ 1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 1.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 1.    0.29  1.    0.    0.    0.    0.    0.  ]
 [ 1.    0.43  2.    1.    0.    0.    0.    0.  ]
 [ 1.    0.57  2.    0.6   1.    0.    0.    0.  ]
 [ 1.    0.71  1.67  0.25  0.61  1.    0.    0.  ]
 [ 1.    0.86  1.67  0.9   0.77 -0.45  1.    0.  ]
 [ 1.    0.14  1.    0.75 -0.64  0.41 -0.79  0.  ]]


In [26]:
print(U) # upper triangular matrix

[[     1.        1.        1.        1.        1.        1.        1.
       1.  ]
 [     0.        3.5      19.25     90.12    409.06   1844.28   8302.77
   37365.95]
 [     0.        0.       -1.5     -14.25    -95.62   -557.81  -3021.66
  -15644.96]
 [     0.        0.        0.        4.99     57.5     433.75   2726.88
   15525.94]
 [     0.        0.        0.        0.        3.03     43.7     392.
    2815.48]
 [     0.        0.        0.        0.        0.        3.19     49.42
     469.09]
 [     0.        0.        0.        0.       -0.        0.        0.85
      22.29]
 [     0.        0.        0.        0.       -0.        0.        0.
       3.99]]


In [27]:
print(b_new) # this is new b after gaussian elimination

[[ 2.1 ]
 [17.  ]
 [-1.37]
 [ 0.33]
 [-0.07]
 [ 0.05]
 [-0.02]
 [-0.08]]


In [13]:
# Back Substitutiom

n = len(b)
x = np.zeros(n)
for row in range(n-1, -1, -1): 
    sum_ax = np.dot(U[row, row+1:], x[row+1:])
    x[row] = (b_new[row][0] - sum_ax) / U[row, row]
    print("Back substituting got x row", row, ":", x[row])
x = x.reshape(-1, 1)
# x.shape, x, len(x), x[0][0]


Back substituting got x row 7 : -0.01937192914301753
Back substituting got x row 6 : 0.48551995485071275
Back substituting got x row 5 : -4.656850007019507
Back substituting got x row 4 : 22.360333101570312
Back substituting got x row 3 : -57.78841328491206
Back substituting got x row 2 : 80.06042994406137
Back substituting got x row 1 : -51.93256529818258
Back substituting got x row 0 : 13.590917518774773


In [14]:
# 4) final polynomial :
# printing values of coefficients x1 to x8
for i in range(len(x)):
    print(round(x[i][0], 2))

13.59
-51.93
80.06
-57.79
22.36
-4.66
0.49
-0.02


In [15]:
# 5) Estimating the amount of solute when a = 3.8
a_value = 3.8
g_sum = 0 # for storing final answer
for i in range(len(x)):
    g_sum  += (x[i][0])*(a_value**i)
print(round(g_sum,2))

14.15
